%YAML:1.0
# lidar features
min_plane_dis: 0.2

min_match_sq_dis: 1.0

corner_filter_size: 0.2
surf_filter_size: 0.4
map_filter_size: 0.6

# window sizes
window_size: 7  #indoor is 12
opt_window_size: 5 #indoor is 7

init_window_factor: 1 #indoor is 2

# Extrinsic parameter between IMU and Camera (adapted from VINS-mono)
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Don't know anything about extrinsic parameters. You don't need to give R,T. We will try to calibrate it. Do some rotation movement at beginning.
opt_extrinsic: 1

extrinsic_rotation: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  data: [1,  0,  0,
         0,  1,  0,
         0,  0,  1]  #TODO 对于我们的场景需要修改
 
 #Translation from imu frame to laser frame, laser^T_imu
extrinsic_translation: !!opencv-matrix
  rows: 3
  cols: 1
  dt: d
  data: [-2.4, 0, 0.7] #TODO 对于我们的场景需要修改

# optimization options
run_optimization: 1

update_laser_imu: 1 #update the optimized states, just for debugging
gravity_fix: 1

plane_projection_factor: 0

imu_factor: 1
point_distance_factor: 1

prior_factor: 0

marginalization_factor: 1

odom_io: 3 #前端每隔几帧发布一次结果

pcl_viewer: 0

# IMU noises
acc_n: 0.2   #acc测量噪声强度
gyr_n: 0.02  #gyr测量噪声强度
acc_w: 0.0002 #acc bias随机游走的强度
gyr_w: 2.0e-5 #gyr bias随机游走的强度
g_norm: 9.80

# lidar deskew
enable_deskew: 1
cutoff_deskew: 0 #1：turn off deskewing, when using corrected point cloud data, like KITTI.

keep_features: 0 #indoor is 1

msg_time_delay: 0.05 #the time offset between lidar and IMU